#!/bin/bash

#Pulling Node latest for openclaw and installing nodejs
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
sudo apt-get install -y nodejs

#Checking the versions
node -v
npm -v

#Installing Openclaw through Ollama
ollama launch openclaw

