# fast_scan.yaml demonstrating named parameter group configurations
---

# Atomic Static Groupings
named_static_groups:
  # QK Norm
  - named_group: "no_qk_norm"
    use_qk_norm: [false]
    use_qk_norm_scale: [false]
  - named_group: "qk_norm"
    use_qk_norm: [true]
    use_qk_norm_scale: [true]

  # RMSNorm Variations
  - named_group: "rmsnorm_all"
    named_group_settings:
      norm_variant_attn: ["rmsnorm"]
      norm_variant_output: ["rmsnorm"]
  - named_group: "hsnorm_all"
    named_group_settings:
      norm_variant_attn: ["hyperspherenorm"]
      norm_variant_output: ["hyperspherenorm"]

  # Norm Type
  - named_group: "pre_ln"
    use_pre_ln: [true]
    use_peri_ln: [false]
    use_post_ln: [false]
  - named_group: "peri_ln"
    use_pre_ln: [true]
    use_peri_ln: [true]
    use_post_ln: [false]
  - named_group: "post_ln"
    use_pre_ln: [true]
    use_peri_ln: [false]
    use_post_ln: [true]

  # Position Embeddings
  - named_group: "rotary"
    named_group_settings:
      use_rotary_embeddings: [true]
      use_abs_pos_embeddings: [false]
  - named_group: "abs"
    named_group_settings:
      use_rotary_embeddings: [false]
      use_abs_pos_embeddings: [true]

named_variation_groups:
  - named_group: "pe_var"
    named_group_alternates: ["rotary", "abs"]
  - named_group: "norm_var"
    named_group_alternates: ["rmsnorm_all", "hsnorm_all"]
  - named_group: "arch_var"
    named_group_alternates: ["pre_ln", "peri_ln"]

# Common_group: parameters applied to every run, but omitted from run names
common_group:
  dataset: ["shakespeare_char"]
  n_layer: ["1"]
  block_size: ["16"]
  batch_size: ["1"]
  max_iters: [500]
  eval_interval: [500]
  eta_variant: ["iteration"]
  device: ["cuda"]
  dtype: ["bfloat16"]
  never_save_checkpoint: [true]
  compile: [false]

# Parameter_groups: define sets of overrides to apply on top of base params
parameter_groups:
  - named_group_variations: ["arch_var", "norm_var", "pe_var"]

