# mlp_cproj_comparison.yaml
---
parameter_groups:
  # Baseline: default down projection
  - mlp_cproj_scale: [1.0]
    tensorboard_run_name: ["default_settings"]
    print_model_stats: ["default_settings.csv"]
  # L2 normalize activation vectors
  - mlp_cproj_scale: [1.0]
    mlp_post_act_l2_norm: [true]
    tensorboard_run_name: ["only_post_activation_norm"]
    print_model_stats: ["only_post_activation_norm.csv"]
  # L2 normalize activation vectors and cproj_scale
  - mlp_cproj_scale: [50]
    mlp_post_act_l2_norm: [true]
    tensorboard_run_name: ["c-proj-scale_and_post-act-norm"]
    print_model_stats: ["c-proj-scale_and_post-act-norm.csv"]
  # only cproj scale
  - mlp_cproj_scale: [50]
    mlp_post_act_l2_norm: [false]
    tensorboard_run_name: ["only_cproj_scale"]
    print_model_stats: ["only_cproj_scale.csv"]

# mlp variations
mlp_variant: ["mlp"]
activation_variant: ["gelu"]

# Modern Model Settings
use_rotary_embeddings: [true]
use_abs_pos_embeddings: [false]
use_qk_norm: [true]
use_qk_norm_scale: [true]
use_peri_ln: [true]

# Training Variations
max_iters: [5000]
warmup_iters: [500]
eval_interval: [500]
n_embd: [384]
n_layer: [6]
n_head: [6]
block_size: [256]
batch_size: [32]
dtype: ["float16"]
dataset: ["minipile"]

# Tracking
compute_model_stats: [true]

# VRAM and Memory
compile: [true]
never_save_checkpoint: [true]

