---
parameter_groups:
  - optimizer: ["adamw"]
    use_speedrun_optim_defaults: [true]
  - optimizer: ["muon"]
    use_speedrun_optim_defaults: [true]
    muon_momentum: [0.95]

# Compact GPT-2 style hyperparameters for a quick comparison run.
n_layer: [6]
n_head: [6]
n_embd: [384]
block_size: [256]
batch_size: [64]
max_iters: [10000]
eval_interval: [1000]
eta_variant: ["iteration"]
dataset: ["minipile"]
device: ["cuda"]
dtype: ["float16"]
use_abs_pos_embeddings: [false]
use_rotary_embeddings: [true]
use_qk_norm: [true]
use_qk_norm_scale: [true]
use_peri_ln: [true]
softmax_variant_attn: ["softmax"]
compile: [true]
never_save_checkpoint: [true]
tensorboard_run_name: ["muon_speedrun_defaults"]
