# sample.yaml demonstrating named parameter group configurations
---
compute_model_stats: [true]
print_model_stats: ["print_stats/${RUN_NAME}"]
print_model_stats_table: ["print_stats/${RUN_NAME}.csv"]

# Atomic Static Groupings
named_static_groups:
  - named_group: "rotary_qk_norm_peri"
    named_group_settings:
      use_rotary_embeddings: [true]
      use_abs_pos_embeddings: [false]
      use_qk_norm: [true]
      use_qk_norm_scale: [true]
      use_pre_ln: [true]
      use_peri_ln: [true]
      use_post_ln: [false]
  - named_group: "slerp_residuals"
    named_group_settings:
      attn_residual_combination: ["slerp"]
      mlp_residual_combination: ["slerp"]
  - named_group: "hypersphere_norms"
    named_group_settings:
      norm_variant_wte: ["hyperspherenorm"]
      norm_variant_attn: ["hyperspherenorm"]
      norm_variant_output: ["hyperspherenorm"]
      hsnorm_scale: [5.0]

# Higher Level Groupings
named_variation_groups:
  - named_group: "default_model_width"
    parameter_groups:
      - n_embd: 768
        n_head: [12]
      - n_embd: 1024
        n_head: [16]
  - named_group: "default_model_depth"
    parameter_groups:
      - n_layer: [12]
      - n_layer: [24]

# Common_group: parameters applied to every run, but omitted from run names
common_group:
  dataset: ["shakespeare_char"]
  block_size: ["1024"]
  batch_size: ["8"]
  device: ["cuda"]
  dtype: ["bfloat16"]
  compile: [true]
  never_save_checkpoint: [true]

# Parameter_groups: define sets of overrides to apply on top of base params
parameter_groups:
  - run_name: ["rotary_default_stats"]
    named_group_static:
      - "rotary_qk_norm_peri"
      - "slerp_residuals"
      - "hypersphere_norms"
    named_group_variations:
      - "default_model_width"
      - "default_model_depth"
