# sample.yaml demonstrating named parameter group configurations with shared libraries
---

# Pull in pre-defined named groups from an adjacent library file
named_group_libraries:
  - "named_group_library.yaml"

# Common_group: parameters applied to every run, but omitted from run names
common_group:
  dataset: ["shakespeare_char"]
  n_layer: ["2"]
  block_size: ["32"]
  batch_size: ["8"]
  max_iters: [750]
  device: ["cuda"]
  dtype: ["bfloat16"]
  never_save_checkpoint: [true]

# Parameter_groups: define sets of overrides to apply on top of base params
parameter_groups:
  - compile: [true, false]
    named_group_static: ["qk_norm", "pre_ln"]
    named_group_variations:
      - "embedding_head_variations"
      - "positional_embeddings"
    named_group_alternates: ["rmsnorm_all", "rmsnorm_attn_hsnorm_out"]
  - compile: [true, false]
    named_group_static: ["no_qk_norm", "peri_ln"]
    named_group_variations:
      - "embedding_head_variations"
      - "positional_embeddings"
    named_group_alternates: ["rmsnorm_all", "rmsnorm_attn_hsnorm_out"]

