# smooth_softshrink_comparison.yaml
---
parameter_groups:
  # Baseline MLP
  - mlp_variant: ["mlp"]
    activation_variant: ["gelu"]
  # Baseline Swiglu
  - mlp_variant: ["swiglu"]
    activation_variant: ["silu"]
  # Smooth Softshrink Tanh
  - mlp_variant: ["mlp", "swiglu"]
    activation_variant: ["softshrink_tanh"]
    softshrink_lambda: [0.25, 0.5, 0.75, 1.0]
  # Smooth Softshrink Softplus
  - mlp_variant: ["mlp", "swiglu"]
    activation_variant: ["softshrink_softplus"]
    softshrink_lambda: [0.25, 0.5, 0.75, 1.0]
  # Smooth Softshrink Sqrt
  - mlp_variant: ["mlp", "swiglu"]
    activation_variant: ["softshrink_sqrt"]
    softshrink_lambda: [0.25, 0.5, 0.75, 1.0]

# VRAM and Memory
compile: [true]
never_save_checkpoint: [true]

# Training Settings
dataset: ["minipile"]
max_iters: [18000]
eval_interval: [3000]
eta_variant: ["iteration"]
block_size: [1024]
batch_size: [16]

# Architecture
n_layer: [12]
n_embd: [768, 960]
n_head: [12]

# Position Embeddings
use_rotary_embeddings: [true]
use_abs_pos_embeddings: [false]

# QK Norm and Peri-LN
use_qk_norm: [true]
use_qk_norm_scale: [true]
use_peri_ln: [true]
