# soap_vs_adamw.yaml
---
parameter_groups:
  - optimizer: ["adamw"]
    learning_rate: ["0.003"]
    beta1: [0.9]
    beta2: [0.95]
    adamw_weight_decay: [0.1]
    adamw_eps: ["1e-8"]
  - optimizer: ["soap"]
    learning_rate: ["0.003"]
    beta1: [0.9]
    beta2: [0.999]
    opt_eps: ["1e-12"]
    opt_weight_decay: [0.1]
    shampoo_update_freq: [1]
    soap_graft_lr: [1.0]

# GPT-2 style configuration for a lightweight SOAP/AdamW bake-off
n_layer: [6]
n_head: [6]
n_embd: [384]
block_size: [256]
batch_size: [64]
max_iters: [10000]
eval_interval: [1000]
dataset: ["minipile"]
device: ["cuda"]
dtype: ["float16"]
use_abs_pos_embeddings: [false]
use_rotary_embeddings: [true]
compile: [true]
never_save_checkpoint: [true]
tensorboard_run_name: ["soap_vs_adamw"]
