- common_group:
    dataset: shakespeare_char
    block_size: 128
    batch_size: 12
    learning_rate: 1e-3
    weight_decay: 0.1
    optimizer: adamw
    loss_fn: cross_entropy
    eval_interval: 10
    eval_iters: 5
    log_interval: 5
  sequential_runs:
    - script: train.py
      args:
        max_iters: 20
        loss_fn: cross_entropy
    - script: train_recurrent.py
      resume: true
      output_ckpt: ckpt_lat.pt
      args:
        max_iters: 10
        eval_interval: 5
        log_interval: 1
        latent_steps: 4
        skip_steps: 1
        weight_start: 1.0
        weight_end: 0.5
        recurrent_variant: latent_chaining
        reset_optim: true
    - script: train_mezo.py
      resume: true
      args:
        max_iters: 10
        eval_interval: 5
        log_interval: 1
        mezo_epsilon: 0.001
        mezo_seed: 123
